feat: update dependencies

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,64 +1,69 @@
-name: publish
+name: Release
 on:
   workflow_dispatch:
     inputs:
       dry-run:
-        description: "Dry run? (y/N)"
+        description: "Dry run"
         required: true
-        default: "N"
+        type: boolean
+        default: false
+      bump-dependents-highest-as:
+        description: "Bump dependents highest as"
+        required: false
+        type: choice
+        options:
+          - major
+          - minor
+          - patch
+        default: "major"
 
 jobs:
-  publish:
+  release:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           token: ${{ secrets.GH_TOKEN }}
-          fetch-depth: 0
+          fetch-depth: 200
+          fetch-tags: true
 
-      - uses: actions/setup-node@v3
+      - uses: actions/setup-node@v4
         with:
-          node-version: 18
+          node-version: 20
+
+      - name: Enable Corepack
+        run: corepack enable
 
       - name: Install Dependencies
-        run: yarn install --immutable --immutable-cache
+        run: yarn install --immutable
 
       - name: New version (dry run)
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y')
-        run: yarn lerna version --yes --no-push --exact --conventional-commits --conventional-graduate --changelog-preset conventional-changelog-conventionalcommits --no-git-tag-version --loglevel=verbose
-
+        if: github.ref == 'refs/heads/main' && inputs.dry-run
+        run: yarn version --dry-run --bump-dependents-highest-as=${{ inputs.bump-dependents-highest-as }}
       - name: Configure Git user
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y') == false
+        if: github.ref == 'refs/heads/main' && !inputs.dry-run
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
 
       - name: New version
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y') == false
+        if: github.ref == 'refs/heads/main' && !inputs.dry-run
         run: |
-          yarn lerna version --yes --push --exact --conventional-commits --conventional-graduate --changelog-preset conventional-changelog-conventionalcommits --create-release=github -m 'chore: release [skip ci]'
+          yarn version --create-release=github  --bump-dependents-highest-as=${{ inputs.bump-dependents-highest-as }} -m 'chore: release [skip ci]\n\n%t'
         env:
           HUSKY: 0
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
           YARN_ENABLE_IMMUTABLE_INSTALLS: false
 
-      - uses: actions/setup-node@v3
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y') == false
-        with:
-          node-version: 18
-          registry-url: "https://registry.npmjs.org"
-
-      - run: yarn lerna publish from-git --no-verify-access --yes
-        if: |
-          github.ref == 'refs/heads/main'
-          && contains(github.event.inputs.dry-run, 'y') == false
+      - name: Publish to npm
+        run: |
+          if [ -z "$NODE_AUTH_TOKEN" ]; then
+            echo "Missing env variable NODE_AUTH_TOKEN"
+            exit 1
+          fi
+          echo >> ./.yarnrc.yml
+          echo "npmAuthToken: $NODE_AUTH_TOKEN" >> ./.yarnrc.yml
+          yarn workspaces foreach --all --parallel --no-private npm publish --tolerate-republish
+        if: github.ref == 'refs/heads/main' && !inputs.dry-run
         env:
           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
